### ISSUE TITLE
You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by goxia** [microsoft/SurfaceDeploymentAccelerator#1]
I made an error trying to build the Windows 10 20H1 of the Surface Pro 7.

`You cannot call a method on a null-valued expression.                                                                   At C:\Users\ow\Documents\GitHub\SurfaceDeploymentAccelerator\CreateSurfaceWindowsImage.ps1:781 char:38             + ...  string (,@($global:OSVersion.ToCharArray() | Select-Object -Last 5)) ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                   + CategoryInfo          : InvalidOperation: (:) [], RuntimeException                                                    + FullyQualifiedErrorId : InvokeMethodOnNull                          `

**Comment by cluberti** [comment]
Currently 20h1 is not supported, although it will be added on release.  That section is dynamically building an aka.ms link that will match a published one, but such a link won't exist until Surface releases an MSI or certifies an MSI for 20h1.

Please check back when 20h1 officially ships and is supported for the next major update of this script which will support it.

**Comment by goxia** [comment]
> Currently 20h1 is not supported, although it will be added on release. That section is dynamically building an aka.ms link that will match a published one, but such a link won't exist until Surface releases an MSI or certifies an MSI for 20h1.
> 
> Please check back when 20h1 officially ships and is supported for the next major update of this script which will support it.

I tested version 1909 and it went wrong.

**Comment by cluberti** [comment]
Hm....  Can you give the parameters and options passed?  That function is building the dynamic aka.ms link based on product and version of Windows 10 you're using, so it shouldn't fail on a supported OS version like 1909.  If you give me the parameters used, I can see if I can figure out what's happening.

**Comment by cluberti** [comment]
Please refresh to 1.1.0 and let me know if the issue persists.  I cannot repro this behavior with 1.1.0 either, so I'm curious if you can.

**Comment by goxia** [comment]
> Please refresh to 1.1.0 and let me know if the issue persists. I cannot repro this behavior with 1.1.0 either, so I'm curious if you can.

I'll give feedback when I have the test results. Thank you.

**Comment by goxia** [comment]
> Please refresh to 1.1.0 and let me know if the issue persists. I cannot repro this behavior with 1.1.0 either, so I'm curious if you can.

"pro not found in install.wim on c:\resources\cn_windows_10_consumer_1909.iso. please make sure to use an ISO file that contains pro, and try again."

**Comment by cluberti** [comment]
So does the ISO have a Pro Index?  The script says it doesn't when parsed.

**Comment by goxia** [comment]
> So does the ISO have a Pro Index? The script says it doesn't when parsed.

Yes, I'm sure. the ISO have a Pro Index.

**Comment by cluberti** [comment]
OK, please provide repro steps, including files used, so I can try and fix this.  Thank you!

**Comment by goxia** [comment]
> OK, please provide repro steps, including files used, so I can try and fix this. Thank you!

`.\CreateSurfaceWindowsImage.ps1 -iso "C:\Resources\cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd.iso" -DestinationFolder C:\Temp -Architecture x64 -Device SurfacePro7 -Office365 $true -CreateISO $true`

The ISO file download from MSDN Subscriptions.

Thank you.

**Comment by cluberti** [comment]
Thank you - I'll see what I come up with.  My apologies you have been hitting an issue for this long!

**Comment by cluberti** [comment]
Yes, string matching on the SKU is what is causing this.  I'm probably going to have to handle these specifically in a languages XML as handling these in a switch might be a bit much to maintain.  I wish I knew how to translate this, but I'll ask Bing to help me on this one and add a quick fix for now in an upcoming 1.2.x drop.

**Comment by goxia** [comment]
> Yes, string matching on the SKU is what is causing this.  I'm probably going to have to handle these specifically in a languages XML as handling these in a switch might be a bit much to maintain.  I wish I knew how to translate this, but I'll ask Bing to help me on this one and add a quick fix for now in an upcoming 1.2.x drop.

Maybe I can help you translate it。

**Comment by cluberti** [comment]
I have a fix in a private branch (1.2.1) that will get merged into testing this week at some point in the near future - I am building a matching XML file that will include the SKUs to match, so people can edit it in the future to make their own matching rules.  It's going to take a bit to run through this and make sure it works, but so far, it does seem to work if I make a unicode XML file and include the proper strings.  PowerShell is parsing "Pro" and "Enterprise" properly with these changes.

My quick XML test so far contains this, which is being parsed and then pattern-matched:

`<Windows10>
    <Editions>
        <Pro>
            <Variants>
                
                <Variant name="Windows 10 Pro"/>
                <Variant name="Windows 10 Pro Evaluation"/>
                <Variant name="Windows 10 专业版"/>
            </Variants>
        </Pro>
        <Enterprise>
            <Variants>
                <Variant name="Windows 10 Enterprise"/>
                <Variant name="Windows 10 Enterprise Evaluation"/>
                <Variant name="Windows 10 Enterprise LTSC"/>
                <Variant name="Windows 10 企业版"/>
            </Variants>
        </Enterprise>
    </Editions>
</Windows10>`


Obviously this will be built out in the future, but for now this is how I'm approaching this.

**Comment by cluberti** [comment]
```
 *********************************************
 *                                           *
 *       Parameters passed to script:        *
 *                                           *
 *********************************************

ISO path:                     D:\Sources\cn_windows_10_business_editions_version_1903_updated_jan_2020_x64_dvd_9e0cca89.iso
OS SKU:                       Pro
Architecture:                 x64
Output:                       D:\Temp
  .NET 3.5:                   True
  Servicing Stack:            True
  Cumulative Update:          True
  Cumulative DotNet Updates:  True
  Adobe Flash Player Updates: True
  Office 365 install:         False
  Device drivers:             SurfaceLaptop3Intel
  Create USB key:             False
  Create ISO:                 False


Mounting ISO D:\Sources\cn_windows_10_business_editions_version_1903_updated_jan_2020_x64_dvd_9e0cca89.iso...
ISO successfully mounted at G:

Parsing install.wim file(s) in G: for images...
Checking G:\sources\install.wim for valid images...
Found image matching Pro :
Path:          G:\sources\install.wim
Index:         5
Name:          Windows 10 专业工作站版
Version:       10.0.18362.592
Architecture:  x64

Mounting G:\sources\install.wim in C:\Users\clube\AppData\Local\Temp\Mount\Scratch...
```

**Comment by goxia** [comment]
> ```
>  *********************************************
>  *                                           *
>  *       Parameters passed to script:        *
>  *                                           *
>  *********************************************
> 
> ISO path:                     D:\Sources\cn_windows_10_business_editions_version_1903_updated_jan_2020_x64_dvd_9e0cca89.iso
> OS SKU:                       Pro
> Architecture:                 x64
> Output:                       D:\Temp
>   .NET 3.5:                   True
>   Servicing Stack:            True
>   Cumulative Update:          True
>   Cumulative DotNet Updates:  True
>   Adobe Flash Player Updates: True
>   Office 365 install:         False
>   Device drivers:             SurfaceLaptop3Intel
>   Create USB key:             False
>   Create ISO:                 False
> 
> 
> Mounting ISO D:\Sources\cn_windows_10_business_editions_version_1903_updated_jan_2020_x64_dvd_9e0cca89.iso...
> ISO successfully mounted at G:
> 
> Parsing install.wim file(s) in G: for images...
> Checking G:\sources\install.wim for valid images...
> Found image matching Pro :
> Path:          G:\sources\install.wim
> Index:         5
> Name:          Windows 10 专业工作站版
> Version:       10.0.18362.592
> Architecture:  x64
> 
> Mounting G:\sources\install.wim in C:\Users\clube\AppData\Local\Temp\Mount\Scratch...
> ```

Is this using the test branch?

**Comment by cluberti** [comment]
Yes, apologies, this is in the testing branch as of right now.  It will get merged into master when the bugs in this version are ironed out to the point I can't find them anymore :).
