### ISSUE TITLE
SurfacePro3

### ISSUE THREAD

**Issue by AlexanderRydberg** [microsoft/SurfaceDeploymentAccelerator#10]
Would it be possible to add SurfacePro3 to the Accelerator? Tried manually changing the url but I failed to find a aka.ms-url for drivers :/

**Comment by cluberti** [comment]
Unfortunately SP3 does not technically get supported here, and the last MSI update was from early last year to provide 19H1 support.

However, all is not lost - if you were to use the "Custom" type from the testing branch, and extract the SurfacePro3_Win10_18362_1902002_0.msi MSI file into a folder and pass that folder as the driver source, it will work via the UseLocalDriverPath/LocalDriverPath parameters.  If you want the resulting files to say "SurfacePro3" in their names and look better than "custom" in the output, edit the "Device" parameter (line 127 of CreateSurfaceWindowsImage.ps1 currently) and add 'SurfacePro3' to the list.  You can now pass SurfacePro3, and if you use the UseLocalDriverPath/LocalDriverPath parameters it will skip trying aka.ms links and instead use the extracted MSI folder you specify.  This will give you what you need, unfortunately we had to make a decision and reimaging Pro3 wasn't high on our list of things to add given it's age.

Hopefully this helps!

**Comment by AlexanderRydberg** [comment]
Ah thank you so much! That solves it :)
