### ISSUE TITLE
Insert Autopilot json

### ISSUE THREAD

**Issue by Purple-IT** [microsoft/SurfaceDeploymentAccelerator#14]
Possibility to import autopilot json to reimaged bare metal Surface device from location. That would make a big difference!

**Comment by cluberti** [comment]
Need context on why Autopilot json would be needed in a scenario where you'd not be migrating from a previous OS?  Need context on why this is a good idea please.

**Comment by cluberti** [comment]
Please re-open if you can articulate the benefits to this enhancement.  Closing for now due to lack of response.
