### ISSUE TITLE
'SurfaceBook3' missing in 'Device' parameter possible values enum

### ISSUE THREAD

**Issue by FabledDugong** [microsoft/SurfaceDeploymentAccelerator#15]
Currently using Surface Deployment Accelerator v1.2.5.3 - when I executed the script with the `-Device SurfaceBook3` param, I didn't receive any error correcting me there is no such value, as I fx. received when trying to execute `-Device SurfaceLaptop3` without specifying the CPU vendor SKU 'am targeting.

**Comment by cluberti** [comment]
SurfaceBook3 is indeed in the ValidateSet for the Device parameter.  Can you explain what issues you're seeing?  I've just run 1.2.5.3 with SurfaceBook3 and it worked properly, and downloaded the right MSI for Book3 and the image worked:
![image](https://user-images.githubusercontent.com/15161578/94890442-1d38bc00-0434-11eb-8f47-df5a017e5f73.png)

**Comment by FabledDugong** [comment]
I am so sorry @cluberti . What I failed to mention in my comment was that the `SurfaceBook3` value is missing in the `README.md` paramaters enum, please see the screenshot attached.

![Annotation 2020-10-02 085344](https://user-images.githubusercontent.com/20367176/94896051-ec38a580-048c-11eb-8393-6ae2a0ddac31.png)

**Comment by cluberti** [comment]
Understood - noticed I was missing SurfaceGo2 as well.  Resolved in master and testing.
