### ISSUE TITLE
Issue downloading 

### ISSUE THREAD

**Issue by gwblok** [microsoft/SurfaceDeploymentAccelerator#16]
When running the process, and it gets to downloading Updates, it fails to grab updates
![image](https://user-images.githubusercontent.com/26312309/105093266-1330dc80-5a68-11eb-8a10-fa9e78968a87.png)

Then it shows that it didn't find any updates at all
![image](https://user-images.githubusercontent.com/26312309/105093384-41162100-5a68-11eb-9fb0-8dc196840400.png)

**Comment by cluberti** [comment]
Thank you for reporting this - the bug is being investigated.  Status will be provided when a fix is checked into the testing branch.

**Comment by cluberti** [comment]
This should be resolved with the latest PR in stable.
