### ISSUE TITLE
Error downloading - "The remote server returned an error: (301) Moved Permanently."

### ISSUE THREAD

**Issue by MarkusRuppel** [microsoft/SurfaceDeploymentAccelerator#18]
With SDA 1.2.5.4, trying to build an Enterprise image Windows 10 (OSVersion:  10.0.19042, ReleaseId:  2009) for SurfaceBook3, there are download errors (see attached images) for some of the the SB3 drivers (Net drivers worked fine), VisualC++ runtimes (2013 x86/x64; 2019 x86/x64) and O365.
![image](https://user-images.githubusercontent.com/78382837/106572502-c6093c00-6538-11eb-96bb-195e23ecbc75.png)
![image](https://user-images.githubusercontent.com/78382837/106577833-23a08700-653f-11eb-9dba-e78f67d713ad.png)
To allow for completion of the script, Office365 had to be set to $False.

Subsequently, the respective files could not be added to the wim file.
![image](https://user-images.githubusercontent.com/78382837/106579999-aaeefa00-6541-11eb-8ecf-f76919151015.png)

Please let me know how to fix this or fix the otherwise excellent script. Thanks!

Best regards, 

Markus Ruppel

**Comment by MarkusRuppel** [comment]
Well, looks like I overlooked the requirement not to use PSCore 6/7... running on the desktop version 5.1 took care of the above stated issue. Please consider this closed. 
Regarding #19, I'll report back as soon as the newly created installation sources have been tested. Same applies to the minor issue stated in #20, but I assume that this might not relate to the PS environment used to build the installation sources.

Thx,
Markus Ruppel

**Comment by cluberti** [comment]
I would like to eventually support PSCore, but unfortunately this is not something that will happen in the near term.
