### ISSUE TITLE
ProductKey installation failed (0x80070057)

### ISSUE THREAD

**Issue by goxia** [microsoft/SurfaceDeploymentAccelerator#2]
ProductKey installation failed (0x80070057) at specialize phase.
check the unattend.xml file to find that the product default to an empty value.

**Comment by cluberti** [comment]
Please make certain that the Unattend.xml that matches the version you are deploying has the KMS setup key for that SKU and retest:

https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys

**Comment by cluberti** [comment]
I believe my recent check-in to master should resolve this - for some reason the XML was created with a blank key instead of a blank element.  This should be fixed now.

**Comment by goxia** [comment]
> I believe my recent check-in to master should resolve this - for some reason the XML was created with a blank key instead of a blank element. This should be fixed now.

Thanks a lot.
