### ISSUE TITLE
"Reboot" Popup during install from USB

### ISSUE THREAD

**Issue by MarkusRuppel** [microsoft/SurfaceDeploymentAccelerator#20]
The following popup was displayed during the initial install from USB on a Surface Book 3:

![image](https://user-images.githubusercontent.com/78382837/106595886-851f2080-6554-11eb-9318-33cc04d974a7.png)

Furthermore, at that point during the installation, keyboard, touchpad, and screen touch are not available (possibly caused by missing drivers, see #18 ??), and one needs to connect an external mouse to respond to the prompt. 

Is there a parameter or other means to prevent this popup and guarantee uninterrupted installation? 

Thanks, 

Markus Ruppel

**Comment by Hafiz-Ali** [comment]
Hi, we are experiencing the same issue here, no keyboard, touchpad, and touch screen. We had a test run after running it on the Surface Pro 9 intel and unfortunately no luck. Could you please help? @cluberti
