### ISSUE TITLE
DCR - Make this tool create Upgrade Media besides just a WIM

### ISSUE THREAD

**Issue by gwblok** [microsoft/SurfaceDeploymentAccelerator#21]
This tool is a good start, but misses a critical piece that makes me leave it on the self and use OSDBuilder instead.
Using this tool, the only output I have is a WIM, great for OSD, not great for Windows Upgrades.
Request:

- Provide the full Media, not just the WIM
- Apply the Dynamic Updates to the Media (Both the ones that update the Setup files, and the ones that get applied to the WIM)

The goal is to use one process to create identical media used for both OSD & in place upgrades.   This is a corporate requirement we have, to prevent drift of machines that are Net-New, and Upgraded.

If I missed an option that already does this, my apologies, this tool is quite amazing and does a lot, thank you.

**Comment by cluberti** [comment]
Can you expand on this request more fully?  This is not meant to replace / replicate setup media, and is not a goal of the tool, so I'd need to understand the ask before I can comment further.

**Comment by gwblok** [comment]
The ask is to update the entire Media (ISO contents), not just the WIM.
I'd see it working something like this:
Copy entire Contents of ISO to SDA Process Folders, ex: D:\SDABuild\Enterprise\10.0.18363\x64\SourceISO
It would then copy it into temp: D:\SDABuild\Enterprise\10.0.18363\x64\ISOMediaTemp
You'd then apply the Setup based Dynamic Updates to the Media

The WIM would be updated as it is in the normal process, and when complete, a new folder would be created:
D:\SDABuild\Enterprise\10.0.18363\x64\CustomMediaContent
Which would include the media you updated with the Dynamic DUs, and the updated install.wim file (Duplicated from the Custom-Install-10.0.18363.1316-Enterprise-2021-02-07_20-55-54.wim file created in the current process)

This would then allow for import into CM as Upgrade Media, or be used to create bootable USB drive using the standard Setup based process. 
DUs: https://ibb.co/Stt0Dzn
[![DU](https://ibb.co/Stt0Dzn)](https://ibb.co/Stt0Dzn)

Since I'm asking, the ability to remove Provisioned AppX Packages would be nice too.

**Comment by cluberti** [comment]
I'll bring this up as a work item for the next version release, but this is currently outside the scope of what SDA does today.  I'll respond back when we're looking at the next major release.

**Comment by cluberti** [comment]
Closing as out of scope.
