### ISSUE TITLE
Sysprep prompt

### ISSUE THREAD

**Issue by FabledDugong** [microsoft/SurfaceDeploymentAccelerator#22]
Hi,
nearing an end of the system deployment with **Pro7+** image, I get a System Preparation Tool 3.14 prompt to choose whether to Generalize the installation, and if OOBE or Audit mode should be entered.

If I tick the Generalize check-box and have the Sysprep reboot to OOBE, an error is thrown and the whole process fails by renderding the system unbootable, please see below screenshot for reference. This step is not present in any other images created by your tool. Any suggestions please? What setting of Sysprep does the tool traditionally use?

Thanks!
![IMG_8958](https://user-images.githubusercontent.com/20367176/107629948-1ed88300-6c63-11eb-8d38-bc84563ac5ca.jpg)

**Comment by cluberti** [comment]
This indicates something in the unattend is trying to parse specialize - that's generally run commands, so it's possible something didn't download properly or get added to the image properly.

While that error is on screen, press Shift+F10 to open a command prompt, and grab the folders and logs from \Windows\Panther and \Windows\Sysprep, and there should be unattendgc folders in there somewhere with setup*.log files.  Those will pinpoint what line in the unattend failed, and hopefully why.

**Comment by cluberti** [comment]
Closing due to no response.
