### ISSUE TITLE
Script not finding available updates

### ISSUE THREAD

**Issue by c-bolen** [microsoft/SurfaceDeploymentAccelerator#23]
Windows 10 updates are not getting added to the image when running the script: 
<img width="599" alt="Screenshot 2021-03-24 163901" src="https://user-images.githubusercontent.com/66373722/112380178-7684f800-8cbf-11eb-8410-b87a979bb97f.png">

**Comment by FabledDugong** [comment]
Same behavior on my end, building an image for Pro 7+.

**Comment by cluberti** [comment]
Unfortunately, catalog changed their web format and it has broken this feature.  We are looking to see if a reasonable fix can be implemented, but I have no ETA as to now.  There are ways to work around this if you know what update you want to include, as the files (if they exist where the script will look for them where it would have downloaded/placed them) will be used if they exist.

**Comment by cluberti** [comment]
Working on this now.
