### ISSUE TITLE
Doesn't find OS Image with specified OSSKU with Win11 ISO File

### ISSUE THREAD

**Issue by technobrain5000** [microsoft/SurfaceDeploymentAccelerator#29]
Hello there

I'm currently struggeling to create Image with a Windows 11 ISO File as a base.
It tells that he can't find an OS Image, then exits and just shows a List with all OS Image Indexes where I can see at Index Nr. 3 the Enterprise Version.

Does anybody know how to resolve this issue?
Thanks in advance for every response.

**Comment by cluberti** [comment]
1.3.0.0 is in testing, and will support Windows 10 and Windows 11 21H2.
