### ISSUE TITLE
How to integrated Office 365 to the deployment

### ISSUE THREAD

**Issue by goxia** [microsoft/SurfaceDeploymentAccelerator#3]
In addition to integrated drivers, can I integrated office 365?

**Comment by cluberti** [comment]
This is not currently implemented, because you will need to enter audit mode, install Office, and then reseal the installation.  That is currently not in scope for the tool at the moment, but it could be added if there's enough appetite.  This is not a simple ask for something meant to work without capture, but I will leave this open for comments.

**Comment by goxia** [comment]
> This is not currently implemented, because you will need to enter audit mode, install Office, and then reseal the installation. That is currently not in scope for the tool at the moment, but it could be added if there's enough appetite. This is not a simple ask for something meant to work without capture, but I will leave this open for comments.

Good idea!

**Comment by cluberti** [comment]
FYI I am working on this for a future release, stay tuned.

**Comment by cluberti** [comment]
Check out the testing branch, 1.2.0, which should have a working O365 C2R install capability.  I've tested it on many devices and it works in test.  Let me know if you can provide any feedback.

**Comment by goxia** [comment]
> Check out the testing branch, 1.2.0, which should have a working O365 C2R install capability. I've tested it on many devices and it works in test. Let me know if you can provide any feedback.

`.\CreateSurfaceWindowsImage.ps1 -iso "C:\Resources\cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd.iso" -DestinationFolder C:\Temp -Architecture x64 -Device SurfacePro7 -Office365 $true -CreateISO $true`
`ISO path:                     C:\Resources\cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd.iso
OS SKU:                       Pro
Architecture:                 x64
Output:                       C:\Temp
  .NET 3.5:                   False
  Servicing Stack:            True
  Cumulative Update:          True
  Cumulative DotNet Updates:  True
  Adobe Flash Player Updates: True
  Office 365 install:         True
  Device drivers:             SurfacePro7
  Create USB key:             False
  Create ISO:                 True


Deleting C:\Users\owner\AppData\Local\Temp\Mount\Scratch\...
Mounting ISO C:\Resources\cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd.iso...
ISO successfully mounted at D:

Parsing install.wim file(s) in D: for images...
Pro not found in install.wim on C:\Resources\cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd.iso.  Please make sure to use an ISO file that contains Pro, and try again.`

**Comment by cluberti** [comment]
Hmm... I wonder if there's a problem parsing characters here, as that looks to be a Chinese ISO?  That should have a Pro, so I'm going to have to download a copy to see if that's right?

**Comment by goxia** [comment]
> Hmm... I wonder if there's a problem parsing characters here, as that looks to be a Chinese ISO? That should have a Pro, so I'm going to have to download a copy to see if that's right?

Yes, It's a Chinese ISO.
Thank you.

**Comment by cluberti** [comment]
Testing branch should have fixes for this at least for Chinese.  I will have to figure out how many languages to add, but the XML should be extensible enough to handle anything now.

**Comment by goxia** [comment]
> Testing branch should have fixes for this at least for Chinese. I will have to figure out how many languages to add, but the XML should be extensible enough to handle anything now.

Looking forward to new developments, thanks.
