### ISSUE TITLE
Typo in WinPE_Drivers.xml 1.3.0.0

### ISSUE THREAD

**Issue by georgalthaus** [microsoft/SurfaceDeploymentAccelerator#38]
There is a typo on line 456:

                <Driver name="surfacewakeontouchcontrol.inf">
should be:

                <Driver name="surfacewakeontouchcontrol.inf"/>

**Comment by gallama1** [comment]
Same issue +1

**Comment by Fvbor** [comment]
Had the same Problem and fixed it in https://github.com/microsoft/SurfaceDeploymentAccelerator/pull/45

**Comment by luy-ce** [comment]
This has been fixed. Apologies for slowness on fixing this in main.
