### ISSUE TITLE
Device list is out of date

### ISSUE THREAD

**Issue by stgeorgesags** [microsoft/SurfaceDeploymentAccelerator#39]
Tried creating an ISO for the SurfaceLaptop4 and the script issued this error:

Cannot validate argument on parameter 'Device'. The argument "SurfaceLaptop4" does not belong to the set "SurfacePro4,SurfacePro5,SurfacePro6,SurfacePro7,SurfacePro7Plus,SurfaceLaptop,SurfaceLaptop2,SurfaceLaptop3Intel,SurfaceLaptop3AMD,SurfaceLaptop4Intel,SurfaceLaptop4AMD,SurfaceLaptopGo,SurfaceBook,SurfaceBook2,SurfaceBook3,SurfaceStudio,SurfaceStudio2,SurfaceGo,SurfaceGoLTE,SurfaceGo2,SurfaceHub2,Custom" specified by the ValidateSet attribute.

**Comment by UrbanCowboy** [comment]
The Surface Laptop 4 is supported. You need to specify if it's for an Intel or AMD Surface Laptop 4. 

SurfaceLaptop4Intel or SurfaceLaptop4AMD

**Comment by stgeorgesags** [comment]
Dude, thanks heaps.
