### ISSUE TITLE
Update integration

### ISSUE THREAD

**Issue by theterminator3000** [microsoft/SurfaceDeploymentAccelerator#5]
When updating the wim with the latest updates, the script will install one update and then save the wim whilst dismounting. It will then remount for the next update. Instead of mounting, patching, saving and dismounting and repeating. Is it possible to have it inject all the updates at once. It may shave some time off the image creation

**Comment by cluberti** [comment]
I'll explain the behavior in a nutshell:

1. When a WIM is found/provided, the script mounts it and runs cleanup against it to make sure it's in a known state.
-- all of these below assume you're downloading updates and not just injecting drivers --
2. It then mounts the WIM again and adds .NET 3.5 and the downloaded Servicing Stack Update, then unmounts/saves the WIM.  This avoids mixing PSFX and non-PSFX updates - this is fixed as of late last year, but I cannot assume the WIM mounted contains the fix easily, and thus we mount, service the Servicing Stack, and unmount / scan to make certain there were no errors.  Also, if you provide an update but are injecting .NET 3.5, the CU needs to be reinstalled if that happens, so the script has to handle that scenario as well.  If there's a desire to shorten this I might be able to add it as a DCR for future versions, but for now safety over speed.
3. It then remounts the WIM, adding the latest CU, unmount/remount (again, PSFX/non-PSFX update issues), and does the same for any Cumulative .NET or Adobe flash updates.  This area is much easier to make faster, so I will take that as a request on the next release.

**Comment by theterminator3000** [comment]
Thanks, that does clear that up for me.
